import { isModified, markSaved } from "./saved";
import { state, type Box } from "./store";
import { getSource } from "./imageProcess";

/**
 * Turning editor state into the on-disk section files (docs/data-format.md) and
 * writing them through the dev-server plugin. For now the loaded sheet *is* the
 * atlas — frames reference rects straight into it — so no repacking happens yet.
 *
 * Each section is saved from the panel that owns it, and `saved.ts` decides
 * which of them still differ from disk.
 */

interface FrameOut {
  x: number;
  y: number;
  w: number;
  h: number;
  anchor: [number, number];
}
interface StepOut {
  frame: string;
  dur: number;
  boxes?: Box[];
}
interface AnimOut {
  loop: boolean;
  steps: StepOut[];
}

/** The `frames` section: id -> rect + anchor. */
export function buildFrames(): Record<string, FrameOut> {
  const frames: Record<string, FrameOut> = {};
  for (const f of state.frames) {
    frames[f.id] = { x: f.x, y: f.y, w: f.w, h: f.h, anchor: f.anchor };
  }
  return frames;
}

/** The `animations` section: name -> { loop, steps }. */
export function buildAnimations(): Record<string, AnimOut> {
  const animations: Record<string, AnimOut> = {};
  for (const a of state.anims) {
    animations[a.name] = {
      loop: a.loop,
      steps: a.steps.map((s) => {
        const out: StepOut = { frame: s.frame, dur: s.dur };
        if (s.boxes.length) out.boxes = s.boxes.map((b) => ({ ...b }));
        return out;
      }),
    };
  }
  return animations;
}

/** The whole entity (used for the Export-JSON fallback download). */
export function getAtlasDataURL(): string | null {
  const source = getSource();
  if (!source) return null;
  const c = document.createElement("canvas");
  c.width = source.width;
  c.height = source.height;
  const ctx = c.getContext("2d");
  if (!ctx) return null;
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(source, 0, 0);
  return c.toDataURL("image/png");
}

/**
 * Guard against silently overwriting someone else's work. The editor is no
 * longer the only writer — animations and states are also generated by scripts
 * — so a section that changed on disk since we loaded it must not be clobbered
 * without the user saying so. Compares the file's mtime with the one we saw.
 */
async function confirmNotStale(section: string): Promise<boolean> {
  const loadedAt = state.sectionMtimes[section];
  if (loadedAt === undefined) return true; // we never loaded it; nothing to lose
  let onDisk: number | undefined;
  try {
    const res = await fetch(`/api/section-mtimes?name=${encodeURIComponent(state.entityName)}`);
    if (!res.ok) return true;
    onDisk = ((await res.json()) as { mtimes: Record<string, number> }).mtimes[section];
  } catch {
    return true; // cannot check — do not block the save
  }
  if (onDisk === undefined || onDisk <= loadedAt) return true;

  return confirm(
    `${section}.json changed on disk after you loaded it — probably a script or another session.\n\n` +
      `Saving now overwrites that change with what is in this editor.\n\n` +
      `OK = overwrite anyway · Cancel = stop (then press "Reload data" to pick the new version up)`,
  );
}

/** Write a single section file (data/entities/<name>/<section>.json). */
async function saveSection(
  section: string,
  data: unknown,
  atlasPngBase64?: string,
): Promise<{ ok: boolean; message: string }> {
  if (!(await confirmNotStale(section))) {
    return { ok: false, message: `Save cancelled — ${section}.json on disk is newer.` };
  }
  try {
    const res = await fetch("/api/section", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: state.entityName, section, data, atlasPngBase64 }),
    });
    const resp = (await res.json()) as { error?: string; atlasWritten?: boolean; mtime?: number };
    if (!res.ok) return { ok: false, message: resp.error ?? "save failed" };
    // Our own write is not a conflict next time round.
    if (resp.mtime !== undefined) state.sectionMtimes[section] = resp.mtime;
    markSaved(section, data);
    return {
      ok: true,
      message:
        `Saved data/entities/${state.entityName}/${section}.json` +
        (resp.atlasWritten ? ` + assets/atlases/${state.entityName}.png` : ""),
    };
  } catch (e) {
    return { ok: false, message: `No editor server (run npm run editor) — ${String(e)}` };
  }
}

/**
 * Snapshot every entity section as matching disk. Called right after an entity
 * is read, so "modified" means changed *since it was opened* rather than
 * "differs from the empty editor".
 */
export function markEntitySaved(): void {
  markSaved("frames", buildFrames());
  markSaved("animations", buildAnimations());
  markSaved("sounds", state.sounds ?? {});
}

/** True when a section holds edits that are not on disk yet. */
export function framesModified(): boolean {
  return isModified("frames", buildFrames());
}

export function animationsModified(): boolean {
  return isModified("animations", buildAnimations());
}

export function entitySoundsModified(): boolean {
  return isModified("sounds", state.sounds ?? {});
}

/** Save the `frames` section (+ the keyed atlas the frames index into). */
export function saveFrames(): Promise<{ ok: boolean; message: string }> {
  return saveSection("frames", buildFrames(), getAtlasDataURL() ?? undefined);
}

/** Save the `animations` section. */
export function saveAnimations(): Promise<{ ok: boolean; message: string }> {
  return saveSection("animations", buildAnimations());
}

/** Save the `sounds` section — this entity's own sounds, never the game bank. */
export function saveSounds(): Promise<{ ok: boolean; message: string }> {
  return saveSection("sounds", state.sounds ?? {});
}

